# Generated by Django 3.2.6 on 2021-08-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formnoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
