# Generated by Django 3.2.6 on 2021-09-01 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formnoo', '0002_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Cours',
            new_name='Categorie',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='title',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='adresse',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='bio',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='types',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ObjetPeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('identifiant', models.CharField(blank=True, max_length=50)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formnoo.categorie')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formnoo.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formnoo.niveau'),
        ),
    ]
